/** Geometry cleanup by terminal roles and topology; no circuit-name selectors. */
import {parseDrawio,getPage,serialize,updateCell} from './model.js';import {cellsOf,localCandidate,genericProposals,rebuildLocalDots} from './generic-refinement.js';import {classify,pinOrderFor} from './components.js';import {getPin} from './stencils.js';import {pinAbs,polylineOf,netGroups} from './route.js';import {connectivityFingerprint,assertGeometryOnly} from './invariant.js';import {mirrorAboutConductionAxis} from './signal-alignment.js';
const pin=(c,i)=>pinAbs(c,getPin(classify(c).shape.key,pinOrderFor(classify(c))[i]));
const anchor=(e,c,w)=>pinAbs(c,{x:Number(e.style.map.get(w+'X')??.5),y:Number(e.style.map.get(w+'Y')??.5)});
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function topology(model){const cs=cellsOf(model),map=new Map(cs.map(c=>[c.id,c])),edges=cs.filter(c=>c.kind==='edge'),nets=netGroups(cs),conduct=new Map();for(const e of edges)for(const [id,w] of [[e.source,'exit'],[e.target,'entry']]){const c=map.get(id);if(classify(c).prefix!=='M')continue;const a=anchor(e,c,w);if(![0,2].some(i=>distance(a,pin(c,i))<.1))continue;const n=nets.get(e.id);if(!conduct.has(n))conduct.set(n,[]);if(!conduct.get(n).some(p=>distance(p,a)<.1))conduct.get(n).push(a);}return {cs,map,edges,nets,conduct};}
export function cleaningMetrics(model){const {cs,map,edges,nets,conduct}=topology(model),grounds=cs.filter(c=>classify(c).role==='ground');let io=0,detour=0,passiveJog=0;
 for(const p of cs.filter(c=>classify(c).role==='port')){const e=edges.find(e=>e.source===p.id||e.target===p.id);if(!e)continue;const other=map.get(e.source===p.id?e.target:e.source),a=anchor(e,p,e.source===p.id?'exit':'entry'),b=anchor(e,other,e.source===other.id?'exit':'entry');if(classify(other).prefix==='M'){if(edges.some(w=>w.source===other.id&&w.target===other.id))continue;const gate=distance(b,pin(other,1))<.1;if(gate){if(a.x>b.x)io++;}else if(a.x<b.x)io++;}}
 for(const [n,pts] of conduct){if(pts.length<2)continue;const x=pts[0].x;if(pts.some(p=>Math.abs(p.x-x)>.1))continue;const ymin=Math.min(...pts.map(p=>p.y)),ymax=Math.max(...pts.map(p=>p.y));for(const e of edges.filter(e=>nets.get(e.id)===n)){const pl=polylineOf(e,map);for(let i=1;i<pl.length;i++){const a=pl[i-1],b=pl[i];if(Math.abs(a.x-b.x)<.1&&Math.abs(a.x-x)>.1&&Math.min(a.y,b.y)>=ymin&&Math.max(a.y,b.y)<=ymax)detour+=Math.abs(a.y-b.y);}}}
 for(const e of edges){const a=map.get(e.source),b=map.get(e.target);if(['R','C','L'].includes(classify(a).prefix)&&['R','C','L'].includes(classify(b).prefix)){const pl=polylineOf(e,map);for(let i=1;i<pl.length;i++){const d=distance(pl[i-1],pl[i]);if(d>.1&&d<20)passiveJog++;}}}
 return {groundSpread:grounds.length?Math.max(...grounds.map(c=>c.y))-Math.min(...grounds.map(c=>c.y)):0,io,detour:Math.round(detour),passiveJog};}
export function cleaningProposals(model,ref,loop){const {cs,map,edges,nets,conduct}=topology(model),out=[];let seq=0;const add=(kind,moves,extra={})=>out.push({id:kind+'-'+(++seq),kind,moves,...extra});
 const carry=moves=>{const ids=new Set(moves.map(m=>m.id));for(const m of [...moves]){for(const e of edges.filter(e=>e.source===m.id||e.target===m.id)){const c=map.get(e.source===m.id?e.target:e.source);if(c&&!ids.has(c.id)&&['ground','power'].includes(classify(c).role)&&edges.filter(e=>e.source===c.id||e.target===c.id).length===1){moves.push({id:c.id,dx:m.dx||0,dy:m.dy||0});ids.add(c.id);}}}return moves;};
 if(loop===1||loop===6){const gs=cs.filter(c=>classify(c).role==='ground');if(gs.length>1){const ys=[Math.max(...gs.map(c=>c.y)),...new Set(gs.map(c=>c.y))];for(const y of ys)add('ground-row',gs.filter(c=>Math.abs(c.y-y)>.1).map(c=>({id:c.id,dy:y-c.y})));}}
 if(loop===2||loop===6){for(const p of cs.filter(c=>classify(c).role==='port')){const ee=edges.filter(e=>e.source===p.id||e.target===p.id);if(ee.length!==1)continue;const e=ee[0],c=map.get(e.source===p.id?e.target:e.source);if(classify(c).prefix!=='M'||edges.some(w=>w.source===c.id&&w.target===c.id))continue;const a=anchor(e,p,e.source===p.id?'exit':'entry'),b=anchor(e,c,e.source===c.id?'exit':'entry'),gate=distance(b,pin(c,1))<.1;
 if(!gate&&a.x<b.x)for(const gap of [70,120,180])add('output-right',[{id:p.id,x:b.x+gap,y:p.y+b.y-a.y,flipH:false}]);
 if(gate&&a.x>b.x){const cl=classify(c),po=pinOrderFor(cl),mirrored=mirrorAboutConductionAxis(c,getPin(cl.shape.key,po[0]),getPin(cl.shape.key,po[2])),g=pin(mirrored,1);for(const gap of [36,60,100])add('input-left',[{id:c.id,mirror:true},{id:p.id,x:g.x-gap-p.w,y:p.y+g.y-a.y,flipH:false}]);}
 }}
 if(loop===3||loop===6){const mos=ref.components.filter(c=>c.prefix==='M');for(const lower of mos){const upper=mos.filter(c=>c.ref!==lower.ref&&c.nodes[2]===lower.nodes[0]);if(upper.length!==1)continue;const pair=[upper[0],lower],uv=map.get(upper[0].ref),lv=map.get(lower.ref);const pm=mos.filter(c=>c.ref!==upper[0].ref&&c.nodes[0]===upper[0].nodes[0]&&/pmos/i.test(classify(map.get(c.ref)).shape.key));const targets=[pin(uv,0).x,...pm.map(c=>pin(map.get(c.ref),0).x)];for(const x of targets)add('conduction-column',carry(pair.map(c=>({id:c.ref,dx:x-pin(map.get(c.ref),0).x}))));}}
 if(loop===5||loop===6){for(const [net,pts] of conduct){if(pts.length<2||pts.some(p=>Math.abs(p.x-pts[0].x)>.1))continue;const ws=edges.filter(e=>nets.get(e.id)===net),ids=[...new Set(ws.flatMap(e=>[e.source,e.target]).filter(id=>classify(map.get(id)).prefix==='M'&&Math.abs(pin(map.get(id),0).x-pts[0].x)<.1))];if(ids.length<2)continue;for(const dx of [80,120,180]){const moves=carry(ids.map(id=>({id,dx})));for(const e of ws)for(const id of [e.source,e.target]){const c=map.get(id);if(classify(c).role==='port'&&!moves.some(m=>m.id===id))moves.push({id,dx});}add('column-expand',moves,{netEdge:ws[0].id,x:pts[0].x+dx});}}}
 if(loop===3||loop===5||loop===6){for(const [net,points] of conduct){if(points.length<2)continue;const ws=edges.filter(e=>nets.get(e.id)===net);if(ws.some(e=>e.style.map.has('drawioApiGateBus')))continue;for(const x of [...new Set(points.map(p=>p.x))]){add('conduction-axis',[],{netEdge:ws[0].id,x});add('conduction-project',[],{netEdge:ws[0].id,x,ymin:Math.min(...points.map(p=>p.y)),ymax:Math.max(...points.map(p=>p.y))});}}}
 if(loop===4){const passive=ref.components.filter(c=>['R','C','L'].includes(c.prefix));
 // Parallel shunts share a node and ground: group them together, capacitor on the left.
 for(const cap of passive.filter(c=>c.prefix==='C'&&c.nodes.includes('0')))for(const res of passive.filter(c=>c.prefix==='R'&&c.nodes.includes('0')&&c.nodes.some(n=>n!=='0'&&cap.nodes.includes(n)))){const a=map.get(cap.ref),b=map.get(res.ref);if(!a||!b)continue;const ax=pin(a,0).x,bx=pin(b,0).x;for(const gap of [130,170,210]){const left=Math.min(ax,bx),moves=[{id:cap.ref,dx:left-gap-ax},{id:res.ref,dx:left-bx,dy:a.y+a.h/2-b.y-b.h/2}];add('parallel-shunts',carry(moves));}}
 // Put adjacent passives on a common terminal row or column.
 for(const e of edges){const a=map.get(e.source),b=map.get(e.target);if(!['R','C','L'].includes(classify(a).prefix)||!['R','C','L'].includes(classify(b).prefix))continue;const u=anchor(e,a,'exit'),v=anchor(e,b,'entry');if(Math.abs(u.y-v.y)<35&&Math.abs(u.y-v.y)>.1)add('passive-row',carry([{id:b.id,dy:u.y-v.y}]));if(Math.abs(u.x-v.x)<90&&Math.abs(u.x-v.x)>.1)add('passive-column',carry([{id:b.id,dx:u.x-v.x}]));}
 }
 if(loop===5||loop===6){out.push(...genericProposals(model,ref,3));for(const e of edges){const a=map.get(e.source),b=map.get(e.target);if(classify(a).prefix!=='M'||classify(b).prefix!=='M'||e.style.map.has('drawioApiGateBus'))continue;const u=anchor(e,a,'exit'),v=anchor(e,b,'entry');const gates=[distance(u,pin(a,1))<.1,distance(v,pin(b,1))<.1];if(gates[0]===gates[1]||Math.abs(u.x-v.x)<250)continue;const mos=cs.filter(c=>classify(c).prefix==='M');for(const y of [Math.min(...mos.map(c=>c.y))-24,Math.max(...mos.map(c=>c.y+c.h))+70])add('outside-feedback',[],{edgeId:e.id,y});}}

 const columns=out.filter(p=>p.kind==='passive-column'),rows=out.filter(p=>p.kind==='passive-row');for(const a of columns)for(const b of rows)if(a.moves[0].id===b.moves[0].id)add('passive-grid',[{...a.moves[0],dy:b.moves[0].dy},...a.moves.slice(1).map(m=>({...m,dy:b.moves.find(v=>v.id===m.id)?.dy||0}))]);
 if(loop===2||loop===6){const inputs=out.filter(p=>p.kind==='input-left'),outputs=out.filter(p=>p.kind==='output-right');for(const a of inputs)for(const b of outputs){const e=edges.find(e=>e.source===b.moves[0].id||e.target===b.moves[0].id);if(e&&(e.source===a.moves[0].id||e.target===a.moves[0].id))add('io-clearance',[...a.moves,...b.moves]);}}
 const seen=new Set();return out.filter(p=>p.moves?.length||p.edges?.length||['conduction-axis','conduction-project','outside-feedback'].includes(p.kind)).filter(({id,...p})=>{const key=JSON.stringify(p);if(seen.has(key))return false;seen.add(key);return true;});}
export function conductionAxisCandidate(xml,p){const doc=parseDrawio(xml),m=getPage(doc),before=connectivityFingerprint(m),{cs,map,edges,nets}=topology(m),net=nets.get(p.netEdge),ws=edges.filter(e=>nets.get(e.id)===net);if(ws.some(e=>e.style.map.has('drawioApiGateBus')))throw Error('Protected gate bus');
 function branch(e,c,w){const a=anchor(e,c,w);if(classify(c).prefix==='M'&&distance(a,pin(c,1))<.1){const d=pin(c,0),side=Math.sign(a.x-d.x);return [a,{x:a.x+side*24,y:a.y},{x:a.x+side*24,y:d.y},{x:p.x,y:d.y}];}return [a,{x:p.x,y:a.y}];}
 for(const e of ws){const a=branch(e,map.get(e.source),'exit'),b=branch(e,map.get(e.target),'entry'),points=[...a,...b.reverse()],clean=[];for(const q of points)if(!clean.length||distance(q,clean.at(-1))>.01)clean.push(q);updateCell(m,e.id,{points:clean.slice(1,-1)});}rebuildLocalDots(m);assertGeometryOnly(before,connectivityFingerprint(m),'conduction axis');return serialize(doc);}
export function conductionProjectionCandidate(xml,p){const doc=parseDrawio(xml),m=getPage(doc),before=connectivityFingerprint(m),{map,edges,nets}=topology(m),ws=edges.filter(e=>nets.get(e.id)===nets.get(p.netEdge));if(ws.some(e=>e.style.map.has('drawioApiGateBus')))throw Error('Protected gate bus');const rails=new Set();for(const e of ws){const pl=polylineOf(e,map);for(let i=1;i<pl.length;i++){const a=pl[i-1],b=pl[i];if(Math.abs(a.x-b.x)<.1&&Math.abs(a.x-p.x)>1&&Math.abs(a.x-p.x)<180&&Math.min(a.y,b.y)>=p.ymin-.1&&Math.max(a.y,b.y)<=p.ymax+.1)rails.add(a.x);}}
 if(!rails.size)throw Error('No local conduction detour');for(const e of ws){const points=e.points.map(q=>q.y>=p.ymin-.1&&q.y<=p.ymax+.1&&[...rails].some(x=>Math.abs(q.x-x)<.1)?{...q,x:p.x}:q);updateCell(m,e.id,{points});}rebuildLocalDots(m);assertGeometryOnly(before,connectivityFingerprint(m),'local conduction projection');return serialize(doc);}
export function columnExpandCandidate(xml,p){const doc=parseDrawio(xml),m=getPage(doc),before=connectivityFingerprint(m),{cs,map,edges}=topology(m),moved=new Map(p.moves.map(v=>[v.id,v]));for(const move of p.moves){const c=map.get(move.id);updateCell(m,c.id,{x:c.x+(move.dx||0),y:c.y+(move.dy||0)});const label=map.get('LBL_'+c.id);if(label)updateCell(m,label.id,{x:label.x+(move.dx||0),y:label.y+(move.dy||0)});}
 const reroute=[];for(const e of edges){if(!moved.has(e.source)&&!moved.has(e.target))continue;if(e.style.map.has('drawioApiGateBus')){const busy=Number(e.style.map.get('drawioApiGateBusY')),points=e.points.map(q=>({...q}));for(const [id,w] of [[e.source,'exit'],[e.target,'entry']])if(moved.has(id)){const a=anchor(e,map.get(id),w),dx=moved.get(id).dx||0;for(const q of points)if(Math.abs(q.x-a.x)<=24.1&&(Math.abs(q.y-a.y)<.1||Math.abs(q.y-busy)<.1))q.x+=dx;}updateCell(m,e.id,{points});}else reroute.push(e.id);}
 const routed=localCandidate(serialize(doc),{edges:reroute});const final=conductionAxisCandidate(routed,{netEdge:p.netEdge,x:p.x});assertGeometryOnly(before,connectivityFingerprint(getPage(parseDrawio(final))),'column expansion');return final;}
export function outsideFeedbackCandidate(xml,p){const doc=parseDrawio(xml),m=getPage(doc),before=connectivityFingerprint(m),{map}=topology(m),e=map.get(p.edgeId);if(e.style.map.has('drawioApiGateBus'))throw Error('Protected gate bus');const path=(c,w)=>{const a=anchor(e,c,w),gate=distance(a,pin(c,1))<.1,side=gate?Math.sign(a.x-pin(c,0).x):Math.sign(a.x-pin(c,1).x);return [a,{x:a.x+side*28,y:a.y},{x:a.x+side*28,y:p.y}];};const points=[...path(map.get(e.source),'exit'),...path(map.get(e.target),'entry').reverse()];updateCell(m,e.id,{points:points.slice(1,-1)});rebuildLocalDots(m);assertGeometryOnly(before,connectivityFingerprint(m),'outside feedback');return serialize(doc);}
export function cleaningCandidate(xml,p){if(p.kind==='outside-feedback')return outsideFeedbackCandidate(xml,p);if(p.kind==='column-expand')return columnExpandCandidate(xml,p);if(p.kind==='conduction-project')return conductionProjectionCandidate(xml,p);return p.kind==='conduction-axis'?conductionAxisCandidate(xml,p):localCandidate(xml,p);}
