import {parseDrawio,getPage,serialize,updateCell} from './model.js';import {cellsOf,rebuildLocalDots} from './generic-refinement.js';import {pinAbs,polylineOf,netGroups} from './route.js';import {connectivityFingerprint,assertGeometryOnly} from './invariant.js';
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),on=(p,a,b)=>Math.abs(dist(a,p)+dist(p,b)-dist(a,b))<.01;
/** Move a port onto an existing same-net trunk, following existing copper to its unchanged terminal. */
export function netTeeCandidate(xml,proposal){const doc=parseDrawio(xml),m=getPage(doc),before=connectivityFingerprint(m),cs=cellsOf(m),map=new Map(cs.map(c=>[c.id,c])),move=proposal.moves[0],port=map.get(move.id),edges=cs.filter(c=>c.kind==='edge'),links=edges.filter(e=>(e.source===port.id||e.target===port.id)&&(!proposal.edgeId||e.id===proposal.edgeId));if(links.length!==1)throw Error('Tee requires one port edge');const e=links[0];if(e.style.map.has('drawioApiGateBus'))throw Error('Protected bus');const net=netGroups(cs),pl=polylineOf(e,map),start=e.source===port.id?pl[0]:pl.at(-1),target=e.source===port.id?pl.at(-1):pl[0],a={x:start.x+(move.dx||0),y:proposal.teeY??(start.y+(move.dy||0))},segs=[];
 for(const w of edges.filter(w=>w.id!==e.id&&net.get(w.id)===net.get(e.id))){const p=polylineOf(w,map);for(let i=1;i<p.length;i++)segs.push([p[i-1],p[i]]);}
 const pts=[a,target,...segs.flat()];for(const [u,v] of segs){if(Math.abs(u.x-v.x)<.01&&a.y>=Math.min(u.y,v.y)&&a.y<=Math.max(u.y,v.y))pts.push({x:u.x,y:a.y});}
 const unique=[];for(const p of pts)if(!unique.some(q=>dist(p,q)<.01))unique.push(p);const adj=unique.map(()=>[]);for(let i=0;i<unique.length;i++)for(let j=i+1;j<unique.length;j++){if(segs.some(([u,v])=>on(unique[i],u,v)&&on(unique[j],u,v))||(i===0&&Math.abs(unique[j].y-a.y)<.01)){const d=dist(unique[i],unique[j]);adj[i].push([j,d]);adj[j].push([i,d]);}}
 const ds=unique.map(()=>Infinity),prev=[],done=new Set();ds[0]=0;for(let k=0;k<unique.length;k++){let u=-1;for(let i=0;i<ds.length;i++)if(!done.has(i)&&(u<0||ds[i]<ds[u]))u=i;if(!Number.isFinite(ds[u]))break;done.add(u);for(const [v,d] of adj[u])if(ds[u]+d<ds[v]){ds[v]=ds[u]+d;prev[v]=u;}}
 const ti=unique.findIndex(p=>dist(p,target)<.01);if(!Number.isFinite(ds[ti]))throw Error('No same-net tee path');const route=[];for(let u=ti;u!==undefined;u=prev[u])route.unshift(unique[u]);if(proposal.teeY!==undefined)route.unshift({x:start.x+(move.dx||0),y:start.y+(move.dy||0)});if(e.source!==port.id)route.reverse();updateCell(m,port.id,{x:port.x+(move.dx||0),y:port.y+(move.dy||0)});updateCell(m,e.id,{points:route.slice(1,-1)});rebuildLocalDots(m);assertGeometryOnly(before,connectivityFingerprint(m),'port same-net tee');return serialize(doc);}
