/** Independent acceptance layer, shared by route, placement and label experiments. */
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {parseDrawio,getPage,serialize,allCells,cellInfo,addVertex} from './model.js';import {extractNetlist} from './netlist.js';import {compare} from './lvs.js';import {auditVisibleConnectivity} from './visible-connectivity.js';import {connectivityFingerprint,assertGeometryOnly} from './invariant.js';import {cellsOf} from './generic-refinement.js';import {routeProtection,copperDominance,visibleNetMetrics} from './conservative-cleaning.js';import {feedbackPenalty} from './feedback-refinement.js';import {labelClearance} from './label-clearance.js';
export function geometryCheck(xml){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'routing-audit-'));try{const p=path.join(dir,'candidate.xml');fs.writeFileSync(p,xml);const r=spawnSync('python3',[fileURLToPath(new URL('../tools/check.py',import.meta.url)),p,'--json'],{encoding:'utf8',timeout:60000,maxBuffer:8*1024*1024});if(![0,1].includes(r.status))throw Error(r.error?.message||r.stderr||'Checker failed');return JSON.parse(r.stdout);}finally{fs.rmSync(dir,{recursive:true,force:true});}}
export function reconcileContactDots(xml){const c=geometryCheck(xml),rs=c.violations.filter(v=>v.rule==='30'||v.rule==='dot-2way');if(!rs.length)return xml;const d=parseDrawio(xml),m=getPage(d);let seq=0;for(const v of rs){const same=c=>c.style.map.get('contactDot')==='1'&&Math.hypot(c.x+c.w/2-v.at[0],c.y+c.h/2-v.at[1])<.1;if(v.rule==='dot-2way'){for(const el of allCells(m))if(same(cellInfo(el)))el.parentNode.removeChild(el);}else if(!cellsOf(m).some(same)){while(cellsOf(m).some(c=>c.id==='V2_DOT_'+seq))seq++;addVertex(m,{id:'V2_DOT_'+seq++,x:v.at[0]-3,y:v.at[1]-3,w:6,h:6,style:'ellipse;fillColor=#000000;strokeColor=#000000;drawioApiJunction=1;contactDot=1;'});}}return serialize(d);}
export function auditRefinement(xml,ref){const m=getPage(parseDrawio(xml));return {lvs:compare(extractNetlist(m),ref).match,visible:auditVisibleConnectivity(m).visible_connectivity_match,check:geometryCheck(xml),labels:labelClearance(m),feedback:feedbackPenalty(m,ref),copper:[...visibleNetMetrics(m).values()].reduce((a,b)=>({length:a.length+b.length,bends:a.bends+b.bends}),{length:0,bends:0})};}
const warnings=c=>{const out={};for(const v of c.violations){if(v.severity!=='warning'||v.rule==='29'&&v.message.includes('conducteurs superposés'))continue;out[v.rule]=(out[v.rule]||0)+1;}return out;};
export function candidateScope(before,after,p){try{assertGeometryOnly(connectivityFingerprint(before),connectivityFingerprint(after),'functional refinement');}catch{return 'electrical identity';}
 if(!['label','passive-bridge'].includes(p.kind))return routeProtection(before,after);
 const allowed=new Set(p.kind==='label'?[p.label]:(p.moves||[]).flatMap(m=>[m.id,'LBL_'+m.id])),old=cellsOf(before),next=new Map(cellsOf(after).map(c=>[c.id,c]));
 for(const c of old){const n=next.get(c.id);if(c.kind==='vertex'&&!allowed.has(c.id)&&c.style.map.get('contactDot')!=='1'&&JSON.stringify([c.x,c.y,c.w,c.h,c.rotation,c.flipH,c.flipV,c.value])!==JSON.stringify(n&&[n.x,n.y,n.w,n.h,n.rotation,n.flipH,n.flipV,n.value]))return 'unrelated placement';if(c.kind==='edge'&&(p.kind==='label'||c.style.map.has('drawioApiFixedRoute')||c.style.map.has('drawioApiGateBus'))&&JSON.stringify(c.points)!==JSON.stringify(n?.points))return 'protected route';}return null;}
export function acceptRefinement(beforeXml,afterXml,p,a,b,baseline){const old=getPage(parseDrawio(beforeXml)),next=getPage(parseDrawio(afterXml));let reason=candidateScope(old,next,p);if(reason)return reason;if(!b.lvs||!b.visible||b.check.errors!==0)return 'electrical/geometry';
 const known=new Set(a.labels.violations.map(v=>JSON.stringify(v)));if(b.labels.violations.some(v=>!known.has(JSON.stringify(v))))return 'new label collision';const w=warnings(a.check);for(const [k,n] of Object.entries(warnings(b.check)))if(n>(w[k]||0)+(p.kind==='passive-bridge'&&a.check.errors>0&&k==='excess-bends'?2:0))return 'warning:'+k;if(b.check.crossings>baseline.check.crossings+2)return 'crossing budget';
 for(const k of Object.keys(a.feedback))if(b.feedback[k]>a.feedback[k])return 'feedback:'+k;
 if(p.kind==='label')return b.labels.count<a.labels.count?null:'no label improvement';if(p.kind==='passive-bridge')return a.check.errors>0?null:'approved placement frozen';return copperDominance(old,next)?null:'no per-net dominance';}
